log4j.logger.ros.mrs_uav_managers=DEBUG
log4j.logger.ros.mrs_uav_trackers=DEBUG
log4j.logger.ros.mrs_uav_controllers=DEBUG
log4j.logger.ros.mrs_uav_odometry=DEBUG
log4j.logger.ros.mrs_bumper=DEBUG
log4j.logger.ros.mrs_mavros_interface=DEBUG
log4j.logger.ros.mrs_uav_testing=DEBUG
